from typing import List, Optional
from pydantic import BaseModel, Field, field_validator, ValidationInfo
import re
from datetime import datetime

class DoctorInfo(BaseModel):
    name: str = Field(..., description="Doctor's full name")
    license_number: str = Field(..., description="Medical license number (State-Digits)", pattern=r"^[A-Z]{2}-\d{5}$")
    dea_number: Optional[str] = Field(None, description="DEA Number (Required for controlled substances)", pattern=r"^[A-Z][A-Z9][0-9]{7}$")
    specialization: Optional[str] = Field(None, description="Doctor's specialization")

class PatientInfo(BaseModel):
    name: str = Field(..., description="Patient's full name")
    id: Optional[str] = Field(None, description="Patient ID (PT#####)", pattern=r"^PT\d{5}$")
    age: Optional[int] = Field(None, description="Patient's age")
    weight: Optional[float] = Field(None, description="Patient's weight in kg (for pediatric dosing)")
    gender: Optional[str] = Field(None, description="Patient's gender")

class Medication(BaseModel):
    name: str = Field(..., description="Name of the medication")
    dosage: str = Field(..., description="Dosage strength with unit (e.g., 500mg)")
    frequency: str = Field(..., description="Intake instructions (e.g., 3 times daily)")
    duration: Optional[str] = Field(None, description="Duration of treatment")
    refills: Optional[int] = Field(0, description="Number of refills allowed")

    @field_validator('dosage')
    @classmethod
    def validate_dosage_format(cls, v: str) -> str:
        # Regex for dosage units: number + optional space + unit
        # Added strict unit check to reject "liters" etc
        pattern = r"^\d+(\.\d+)?\s*(mg|ml|g|mcg|iu|tablets?|capsules?|pills?)$"
        if not re.match(pattern, v, re.IGNORECASE):
             # If it looks like a number but unit is wrong
             raise ValueError(f"Invalid dosage format or unit: {v}. Allowed units: mg, ml, g, mcg, iu, tablet(s)")
        return v

class PrescriptionSchema(BaseModel):
    doctor: DoctorInfo
    patient: PatientInfo
    medications: List[Medication]
    diagnosis: Optional[str] = Field(None, description="Medical diagnosis or indication")
    date: str = Field(..., description="Date of prescription (any format)")
    
    # Validation flags are generated by the Validator agent, not part of the schema input validation
    # but we can include logic to detect them

    def check_controlled_substances(self) -> List[str]:
        """Check for controlled substances without DEA number."""
        warnings = []
        # Enhanced list of controlled substances (could be externalized)
        controlled_drugs = ["morphine", "oxycodone", "fentanyl", "codeine", "hydrocodone", "adderall", "ritalin", "alprazolam", "xanax"]
        
        has_controlled = any(
            any(drug in med.name.lower() for drug in controlled_drugs)
            for med in self.medications
        )
        
        if has_controlled:
            if not self.doctor.dea_number:
                warnings.append("Controlled substance present but DEA Number is MISSING.")
            
        return warnings

    def check_pediatric_dosing(self) -> List[str]:
        """Check for pediatric dosing requirements."""
        warnings = []
        if self.patient.age is not None and self.patient.age < 12:
            if self.patient.weight is None:
                 warnings.append(f"Pediatric patient (Age {self.patient.age}) - MISSING WEIGHT for dosing calculation.")
            else:
                 # Logic to check if weight is reasonable? (Optional)
                 pass
        return warnings
