from typing import List, Optional
from pydantic import BaseModel, Field, field_validator, ValidationInfo
import re
from datetime import datetime

class DoctorInfo(BaseModel):
    name: Optional[str] = Field(None, description="Name of the prescribing doctor")
    license_number: Optional[str] = Field(None, description="Medical license number (State-Digits)")
    dea_number: Optional[str] = Field(None, description="DEA Number (Required for controlled substances)", pattern=r"^[A-Z][A-Z9][0-9]{7}$")
    specialization: Optional[str] = Field(None, description="Doctor's specialization")

class PatientInfo(BaseModel):
    name: Optional[str] = Field(None, description="Patient's full name")
    id: Optional[str] = Field(None, description="Patient ID (PT#####)")
    age: Optional[int] = Field(None, description="Patient's age")
    weight: Optional[float] = Field(None, description="Patient's weight in kg (for pediatric dosing)")
    gender: Optional[str] = Field(None, description="Patient's gender")

class Medication(BaseModel):
    name: Optional[str] = Field(None, description="Name of the medication")
    dosage: Optional[str] = Field(None, description="Dosage strength (e.g., 500mg)")
    frequency: Optional[str] = Field(None, description="Intake instructions")
    duration: Optional[str] = Field(None, description="Duration of treatment")
    refills: Optional[int] = Field(0, description="Number of refills allowed")

    @field_validator('dosage')
    @classmethod
    def validate_dosage_format(cls, v: str) -> str:
        # Accept any string, but check for extreme dosages in separate check
        return v

class PrescriptionSchema(BaseModel):
    doctor: DoctorInfo = Field(default_factory=DoctorInfo)
    patient: PatientInfo = Field(default_factory=PatientInfo)
    medications: List[Medication] = Field(default_factory=list)
    diagnosis: Optional[str] = Field(None, description="Medical diagnosis or indication")
    date: Optional[str] = Field(None, description="Date of prescription (any format)")
    
    # Validation flags are generated by the Validator agent, not part of the schema input validation
    # but we can include logic to detect them

    def check_extreme_dosage(self) -> List[dict]:
        """Flag dosages > 5000mg as LIFE THREATENING."""
        flags = []
        for med in self.medications:
            # Extract numeric value from dosage string (e.g., "5000mg" -> 5000.0)
            if not med.dosage:
                continue
            try:
                match = re.search(r"(\d+(\.\d+)?)", med.dosage)
                if match:
                    val = float(match.group(1))
                    if val > 5000:
                        flags.append({
                            "code": "EXTREME_DOSAGE",
                            "message": f"Life-threatening dosage: {med.dosage} exceeds 5000mg safety limit.",
                            "severity": "CRITICAL"
                        })
            except (ValueError, TypeError):
                continue
        return flags

    def check_controlled_substances(self) -> List[dict]:
        """Check for controlled substances without DEA number."""
        flags = []
        controlled_drugs = ["morphine", "oxycodone", "fentanyl", "codeine", "hydrocodone", "xanax", "percocet"]
        
        has_controlled = any(
            any(drug in (med.name.lower() if med.name else "") for drug in controlled_drugs)
            for med in self.medications
        )
        
        if has_controlled and not self.doctor.dea_number:
            flags.append({
                "code": "CONTROLLED_SUBSTANCE_MISSING_DEA",
                "message": "Controlled substance detected but Physician DEA Number is missing.",
                "severity": "HIGH"
            })
        return flags

    def check_pediatric_dosing(self) -> List[dict]:
        """Check for pediatric dosing requirements."""
        flags = []
        if self.patient.age is not None and self.patient.age < 12:
            if not getattr(self.patient, 'weight', None): # Assuming weight might be added/missing
                 flags.append({
                     "code": "MISSING_PEDIATRIC_WEIGHT",
                     "message": f"Pediatric patient (Age {self.patient.age}) - missing weight for clinical validation.",
                     "severity": "MEDIUM"
                 })
        return flags

    def check_geriatric_polypharmacy(self) -> List[dict]:
        """Flag polypharmacy risk for patients > 65."""
        flags = []
        age = self.patient.age
        if age is not None and age >= 65:
            if self.medications and len(self.medications) > 5:
                flags.append({
                    "code": "GERIATRIC_POLYPHARMACY_RISK",
                    "message": f"Geriatric patient (Age {self.patient.age}) is prescribed {len(self.medications)} medications. High risk of drug interactions.",
                    "severity": "MEDIUM"
                })
        return flags

    def check_missing_dosage(self) -> List[dict]:
        """Flag medications without dosage strength."""
        flags = []
        for med in self.medications:
            if not med.dosage:
                flags.append({
                    "code": "MISSING_DOSAGE",
                    "message": f"Clinical Safety Error: Medication '{med.name}' is missing dosage instructions.",
                    "severity": "MEDIUM"
                })
        return flags

    def check_unit_standards(self) -> List[dict]:
        """Flag non-standard medical units."""
        flags = []
        standard_units = ["mg", "ml", "g", "mcg", "iu", "tablet", "tablets", "capsule", "capsules", "pill", "pills"]
        for med in self.medications:
            dosage_str = med.dosage
            if not dosage_str:
                continue
            # Extract unit (e.g., "500 mg" -> "mg")
            match = re.search(r"[0-9\.]+\s*([a-zA-Z]+)", dosage_str)
            if match:
                unit = match.group(1).lower()
                if unit not in standard_units:
                    flags.append({
                        "code": "NON_STANDARD_UNIT",
                        "message": f"Non-standard unit '{unit}' detected in dosage: {med.dosage}.",
                        "severity": "LOW"
                    })
        return flags

    def check_mandatory_fields(self) -> List[dict]:
        """Flag unauthorized documents (Missing license)."""
        flags = []
        if not self.doctor.license_number or self.doctor.license_number == "null":
            flags.append({
                "code": "MISSING_DOCTOR_LICENSE",
                "message": "Unauthorized document: Doctor license number is missing.",
                "severity": "HIGH"
            })
        return flags
