from typing import List, Optional
from pydantic import BaseModel, Field, field_validator, ValidationInfo
import re
from datetime import datetime


class DoctorInfo(BaseModel):
    name: Optional[str] = Field(
        None, description="Name of the prescribing doctor")
    license_number: Optional[str] = Field(
        None, description="Medical license number (State-Digits)")
    dea_number: Optional[str] = Field(
        None, description="DEA Number (Required for controlled substances) - Format: 2 letters + 7 digits (e.g., AB1234563)")
    specialization: Optional[str] = Field(
        None, description="Doctor's specialization")


class PatientInfo(BaseModel):
    name: Optional[str] = Field(None, description="Patient's full name")
    id: Optional[str] = Field(None, description="Patient ID (PT#####)")
    age: Optional[int] = Field(None, description="Patient's age")
    weight: Optional[float] = Field(
        None, description="Patient's weight in kg (for pediatric dosing)")
    gender: Optional[str] = Field(None, description="Patient's gender")


class Medication(BaseModel):
    name: Optional[str] = Field(None, description="Name of the medication")
    dosage: Optional[str] = Field(
        None, description="Dosage strength (e.g., 500mg)")
    frequency: Optional[str] = Field(None, description="Intake instructions")
    duration: Optional[str] = Field(None, description="Duration of treatment")
    refills: Optional[int] = Field(0, description="Number of refills allowed")

    @field_validator('dosage')
    @classmethod
    def validate_dosage_format(cls, v: Optional[str]) -> Optional[str]:
        """Accept any dosage format - validation flags are generated by validator agent."""
        # Allow any format without strict validation to let data pass through
        # The validator agent will generate flags for data quality issues
        return v


class PrescriptionSchema(BaseModel):
    doctor: DoctorInfo = Field(default_factory=DoctorInfo)
    patient: PatientInfo = Field(default_factory=PatientInfo)
    medications: List[Medication] = Field(default_factory=list)
    diagnosis: Optional[str] = Field(
        None, description="Medical diagnosis or indication")
    date: Optional[str] = Field(
        None, description="Date of prescription (any format)")

    # Validation flags are generated by the Validator agent, not part of the schema input validation
    # but we can include logic to detect them

    def check_extreme_dosage(self) -> List[dict]:
        """Flag dosages > 5000mg as LIFE THREATENING."""
        flags = []
        for med in self.medications:
            # Extract numeric value from dosage string (e.g., "5000mg" -> 5000.0)
            if not med.dosage:
                continue
            try:
                match = re.search(r"(\d+(\.\d+)?)", med.dosage)
                if match:
                    val = float(match.group(1))
                    if val > 5000:
                        flags.append({
                            "code": "EXTREME_DOSAGE",
                            "message": f"Life-threatening dosage: {med.dosage} exceeds 5000mg safety limit.",
                            "severity": "CRITICAL"
                        })
            except (ValueError, TypeError):
                continue
        return flags

    def check_controlled_substances(self) -> List[dict]:
        """Check for controlled substances without DEA number."""
        flags = []
        controlled_drugs = ["morphine", "oxycodone", "fentanyl",
                            "codeine", "hydrocodone", "xanax", "percocet",
                            "alprazolam", "diazepam", "lorazepam", "clonazepam",
                            "adderall", "ritalin", "methylphenidate", "tramadol"]

        has_controlled = any(
            any(drug in (med.name.lower() if med.name else "")
                for drug in controlled_drugs)
            for med in self.medications
        )

        if has_controlled:
            dea = self.doctor.dea_number
            # Check if DEA is missing, null, or invalid
            if not dea or dea == "null" or dea == "":
                flags.append({
                    "code": "CONTROLLED_SUBSTANCE_NO_DEA",
                    "message": "Controlled substance detected but Physician DEA Number is MISSING. Federal requirement for Schedule II-V medications.",
                    "severity": "CRITICAL"
                })
            # If DEA is provided, validate format
            elif not re.match(r"^[A-Z][A-Z9][0-9]{7}$", dea):
                flags.append({
                    "code": "CONTROLLED_SUBSTANCE_INVALID_DEA",
                    "message": f"Controlled substance detected but DEA Number '{dea}' is INVALID. Must be 2 letters + 7 digits (e.g., AB1234563).",
                    "severity": "CRITICAL"
                })
        return flags

    def check_pediatric_dosing(self) -> List[dict]:
        """Check for pediatric dosing requirements and safety."""
        flags = []
        age = self.patient.age
        weight = self.patient.weight

        if age is not None and age < 12:
            # Check for missing weight
            if not weight:
                flags.append({
                    "code": "PEDIATRIC_DOSING",
                    "message": f"Pediatric patient (Age {age}) - MISSING WEIGHT for clinical validation.",
                    "severity": "MEDIUM"
                })

            # Check for abnormal weight for age
            if weight:
                # Approximate normal weight ranges by age group
                weight_ranges = {
                    (0, 1): (3, 12),      # Infants: 3-12 kg
                    (1, 3): (10, 16),     # Toddlers: 10-16 kg
                    (3, 6): (14, 22),     # Preschool: 14-22 kg
                    (6, 12): (20, 45)     # School age: 20-45 kg
                }

                for (min_age, max_age), (min_weight, max_weight) in weight_ranges.items():
                    if min_age <= age < max_age:
                        if weight < min_weight or weight > max_weight:
                            flags.append({
                                "code": "PEDIATRIC_ABNORMAL_WEIGHT",
                                "message": f"Pediatric patient (Age {age}) has abnormal weight {weight}kg (expected {min_weight}-{max_weight}kg). Verify data accuracy.",
                                "severity": "MEDIUM"
                            })
                        break

            # Check for age-inappropriate medications
            pediatric_contraindicated = {
                "atorvastatin": "Statin typically contraindicated in young children",
                "simvastatin": "Statin typically contraindicated in young children",
                "rosuvastatin": "Statin typically contraindicated in young children",
                "aspirin": "Risk of Reye's syndrome in children under 12",
                "tetracycline": "Affects bone/tooth development in children under 8",
                "doxycycline": "Affects bone/tooth development in children under 8",
                "ciprofloxacin": "Risk of cartilage damage in growing children",
                "levofloxacin": "Risk of cartilage damage in growing children",
                "metformin": "Type 2 diabetes medication rarely appropriate for young children",
                "lisinopril": "ACE inhibitor typically not indicated for young children",
                "enalapril": "ACE inhibitor typically not indicated for young children",
                "losartan": "ARB typically not indicated for young children",
                "amlodipine": "Calcium channel blocker rarely appropriate for young children"
            }

            for med in self.medications:
                med_name_lower = (med.name or "").lower()
                for contraindicated_drug, reason in pediatric_contraindicated.items():
                    if contraindicated_drug in med_name_lower:
                        flags.append({
                            "code": "PEDIATRIC_CONTRAINDICATED_MED",
                            "message": f"Pediatric patient (Age {age}) prescribed {med.name} - {reason}. Clinical review required.",
                            "severity": "HIGH"
                        })
                        break

            # Check for excessive dosages based on weight
            if weight:
                for med in self.medications:
                    dosage_str = med.dosage or ""
                    med_name_lower = (med.name or "").lower()

                    # Extract numeric dosage
                    match = re.search(r"(\d+(\.\d+)?)", dosage_str)
                    if match:
                        dosage_val = float(match.group(1))

                        # Paracetamol/Acetaminophen: max 15mg/kg per dose
                        if "paracetamol" in med_name_lower or "acetaminophen" in med_name_lower:
                            if "mg" in dosage_str.lower():
                                max_safe_dose = weight * 15  # 15mg/kg
                                if dosage_val > max_safe_dose:
                                    flags.append({
                                        "code": "PEDIATRIC_EXCESSIVE_DOSE",
                                        "message": f"Pediatric patient ({weight}kg) prescribed {med.name} {dosage_str} - Exceeds safe dose of {max_safe_dose:.0f}mg (15mg/kg). Risk of hepatotoxicity.",
                                        "severity": "CRITICAL"
                                    })

                        # Ibuprofen: max 10mg/kg per dose
                        elif "ibuprofen" in med_name_lower:
                            if "mg" in dosage_str.lower():
                                max_safe_dose = weight * 10  # 10mg/kg
                                if dosage_val > max_safe_dose:
                                    flags.append({
                                        "code": "PEDIATRIC_EXCESSIVE_DOSE",
                                        "message": f"Pediatric patient ({weight}kg) prescribed {med.name} {dosage_str} - Exceeds safe dose of {max_safe_dose:.0f}mg (10mg/kg).",
                                        "severity": "HIGH"
                                    })

        return flags

    def check_polypharmacy(self) -> List[dict]:
        """Flag excessive medication count (polypharmacy risk) for all patients."""
        flags = []
        med_count = len(self.medications) if self.medications else 0

        if med_count >= 10:
            flags.append({
                "code": "EXCESSIVE_POLYPHARMACY",
                "message": f"Patient prescribed {med_count} medications. High risk of drug-drug interactions, adverse effects, and reduced adherence. Clinical review recommended.",
                "severity": "HIGH"
            })
        elif med_count >= 6:
            flags.append({
                "code": "POLYPHARMACY_RISK",
                "message": f"Patient prescribed {med_count} medications. Moderate risk of drug interactions and complexity.",
                "severity": "MEDIUM"
            })

        return flags

    def check_geriatric_polypharmacy(self) -> List[dict]:
        """Flag geriatric medication risks for patients >= 65."""
        flags = []
        age = self.patient.age
        if age is not None and age >= 65:
            # High-risk medications requiring special monitoring in elderly
            geriatric_high_risk = [
                "insulin", "glargine", "warfarin", "digoxin", "lithium",
                "benzodiazepine", "diazepam", "lorazepam", "alprazolam",
                "diphenhydramine", "hydroxyzine", "amitriptyline"
            ]

            # Check for high-risk medications
            for med in self.medications:
                med_name_lower = (med.name or "").lower()
                for risk_drug in geriatric_high_risk:
                    if risk_drug in med_name_lower:
                        flags.append({
                            "code": "GERIATRIC_HIGH_RISK_MED",
                            "message": f"Geriatric patient (Age {age}) prescribed {med.name} - Requires careful dose adjustment and monitoring in elderly.",
                            "severity": "MEDIUM"
                        })
                        break

            # Check for polypharmacy (>5 medications)
            if self.medications and len(self.medications) > 5:
                flags.append({
                    "code": "GERIATRIC_POLYPHARMACY_RISK",
                    "message": f"Geriatric patient (Age {age}) is prescribed {len(self.medications)} medications. High risk of drug interactions.",
                    "severity": "MEDIUM"
                })
        return flags

    def check_missing_dosage(self) -> List[dict]:
        """Flag medications without dosage strength."""
        flags = []
        for med in self.medications:
            if not med.dosage:
                flags.append({
                    "code": "MISSING_DOSAGE",
                    "message": f"Clinical Safety Error: Medication '{med.name}' is missing dosage instructions.",
                    "severity": "MEDIUM"
                })
        return flags

    def check_unit_standards(self) -> List[dict]:
        """Flag non-standard and invalid medical units."""
        flags = []

        # Valid medical units
        valid_units = ["mg", "ml", "g", "mcg", "ug", "iu", "u", "tablet", "tablets",
                       "capsule", "capsules", "pill", "pills", "drop", "drops", "spray",
                       "sprays", "puff", "puffs", "patch", "mg/ml", "unit", "units",
                       "mcg/hr", "mg/hr", "ml/hr", "units/hr", "iu/hr", "%"]

        # Critical invalid units that are dangerous for oral medications
        invalid_critical_units = ["liters", "liter",
                                  "l", "kg", "kgs", "cm", "inches"]

        for med in self.medications:
            dosage_str = med.dosage
            if not dosage_str:
                continue

            # Extract unit (e.g., "500 mg" -> "mg", "7 liters" -> "liters")
            match = re.search(r"[0-9\.]+\s*([a-zA-Z/]+)", dosage_str)
            if match:
                unit = match.group(1).lower()

                # Check for critical invalid units first
                if unit in invalid_critical_units:
                    flags.append({
                        "code": "INVALID_DOSAGE_UNIT",
                        "message": f"CRITICAL: Invalid dosage unit '{unit}' in '{med.name}: {dosage_str}'. This unit is inappropriate for medication dosing and requires clinical review.",
                        "severity": "HIGH"
                    })
                # Check for non-standard units
                elif unit not in valid_units:
                    flags.append({
                        "code": "NON_STANDARD_UNIT",
                        "message": f"Non-standard unit '{unit}' detected in dosage: {med.dosage}.",
                        "severity": "MEDIUM"
                    })
        return flags

    def check_mandatory_fields(self) -> List[dict]:
        """Flag unauthorized documents (Missing license)."""
        flags = []
        if not self.doctor.license_number or self.doctor.license_number == "null":
            flags.append({
                "code": "MISSING_DOCTOR_LICENSE",
                "message": "Unauthorized document: Doctor license number is missing.",
                "severity": "HIGH"
            })
        return flags
